//! Rust struct emitter — walks the AST and produces a `.rs` file.
//!
//! Each generated struct carries **both** XML and protobuf derives on the
//! same type so that a single value can represent a decoded WSDL message
//! and be directly encoded to protobuf for Redpanda:
//!
//! ```text
//! XML bytes  ──serde/quick-xml──►  Rust struct  ──prost──►  proto bytes
//! ```
//!
//! ## Derive strategy
//!
//! | Purpose | Derive |
//! |---|---|
//! | XML decode (WSDL in) | `serde::Deserialize` + `#[serde(rename)]` |
//! | Proto encode (Redpanda out) | `prost::Message` + `#[prost(...)]` |
//! | Proto enums | `prost::Enumeration` + `#[repr(i32)]` |
//!
//! ## Field naming
//!
//! XSD element names (PascalCase) are preserved via `#[serde(rename)]` for
//! XML compatibility. Rust field names are converted to `snake_case`.
//! Names that collide with Rust keywords have `_field` appended.
//!
//! ## Optional and repeated fields
//!
//! | XSD | Rust type |
//! |---|---|
//! | `minOccurs="0"` on a primitive | `Option<T>` |
//! | `minOccurs="0"` on a message | `Option<T>` |
//! | `maxOccurs="unbounded"` | `Vec<T>` |

use crate::mapping::map_primitive;
use crate::parser::ast::*;

/// Emit a `.rs` file containing:
/// - Rust enums for xs:simpleType enumerations (prost + serde)
/// - Rust structs for xs:complexType (prost::Message + serde::Deserialize for XML)
///
/// The structs carry both:
///   - `#[serde(rename = "...")]` for XML decode (incoming WSDL messages)
///   - `#[prost(...)]` for protobuf encode (outgoing Redpanda messages)
pub fn emit(types: &[TypeDef]) -> String {
    let mut out = String::new();

    out.push_str("// Auto-generated by spear-gen. DO NOT EDIT.\n");
    out.push_str("#![allow(clippy::all, dead_code, unused_imports)]\n\n");
    out.push_str("use prost::Message;\n");
    out.push_str("use serde::{Deserialize, Serialize};\n\n");

    for def in types {
        match def {
            TypeDef::Simple(t) => emit_enum(t, &mut out),
            TypeDef::Complex(t) => emit_struct(t, types, &mut out),
        }
        out.push('\n');
    }

    out
}

fn emit_enum(t: &SimpleType, out: &mut String) {
    out.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\n");
    out.push_str("#[derive(Serialize, Deserialize)]\n");
    out.push_str("#[derive(prost::Enumeration)]\n");
    out.push_str("#[repr(i32)]\n");
    out.push_str(&format!("pub enum {} {{\n", t.name));
    for v in &t.variants {
        // Preserve original name for serde; the prost macro uses the repr value.
        out.push_str(&format!(
            "    #[serde(rename = \"{}\")]\n",
            v.name
        ));
        out.push_str(&format!("    {} = {},\n", v.name, v.number));
    }
    out.push_str("}\n");
}

fn emit_struct(t: &ComplexType, all_types: &[TypeDef], out: &mut String) {
    out.push_str("#[derive(Clone, Debug, PartialEq)]\n");
    out.push_str("#[derive(Message)]\n");
    out.push_str("#[derive(Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct {} {{\n", t.name));

    match &t.content {
        ComplexContent::Sequence(fields) => {
            emit_struct_fields(fields, all_types, out, 1);
        }
        ComplexContent::Choice(fields) => {
            out.push_str("    // xs:choice — at most one of these fields will be populated\n");
            emit_struct_fields(fields, all_types, out, 1);
        }
        ComplexContent::Extension { .. } => {
            out.push_str("    // unresolved extension\n");
        }
    }

    out.push_str("}\n");
}

fn emit_struct_fields(fields: &[Field], all_types: &[TypeDef], out: &mut String, start_tag: u32) {
    let mut tag = start_tag;
    for f in fields {
        let (base_type, prost_attr_base) = field_base_type(&f.type_ref, all_types, tag);

        // Insert `repeated` into the prost attribute for Vec fields.
        let prost_attr = if f.repeated {
            prost_attr_base.replacen("tag=", "repeated, tag=", 1)
        } else {
            prost_attr_base
        };

        out.push_str(&format!("    #[prost({})]\n", prost_attr));
        out.push_str(&format!("    #[serde(rename = \"{}\")]\n", f.name));

        // Apply Vec or Option wrapper here — never in field_base_type — to
        // avoid double-wrapping optional message fields.
        let final_type = if f.repeated {
            format!("Vec<{}>", base_type)
        } else if f.optional {
            format!("Option<{}>", base_type)
        } else {
            base_type
        };

        let field_name = escape_keyword(&snake_case(&f.name));
        out.push_str(&format!("    pub {field_name}: {final_type},\n"));
        tag += 1;
    }
}

/// Returns (base_rust_type, prost_attr) without applying Vec/Option wrappers.
/// The caller in emit_struct_fields applies those based on repeated/optional flags.
fn field_base_type(type_ref: &TypeRef, all_types: &[TypeDef], tag: u32) -> (String, String) {
    match type_ref {
        TypeRef::Builtin(p) => {
            let m = map_primitive(*p);
            let prost = format!("{}, tag=\"{}\"", m.prost_tag, tag);
            (m.rust_type.to_owned(), prost)
        }
        TypeRef::Named(name) => {
            let is_enum = all_types
                .iter()
                .any(|t| matches!(t, TypeDef::Simple(s) if s.name == *name));
            if is_enum {
                let prost = format!("enumeration=\"{}\", tag=\"{}\"", name, tag);
                ("i32".to_owned(), prost)
            } else {
                let prost = format!("message, optional, tag=\"{}\"", tag);
                (name.clone(), prost)
            }
        }
    }
}

fn snake_case(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(c.to_lowercase().next().unwrap());
    }
    out
}

/// Append `_field` to names that collide with Rust keywords.
fn escape_keyword(s: &str) -> String {
    match s {
        "type" | "ref" | "fn" | "mod" | "use" | "move" | "match" | "loop" | "if" | "else"
        | "while" | "for" | "in" | "let" | "mut" | "const" | "static" | "return" | "break"
        | "continue" | "struct" | "enum" | "trait" | "impl" | "where" | "pub" | "super"
        | "self" | "Self" | "crate" | "extern" | "unsafe" | "async" | "await" | "dyn"
        | "abstract" | "become" | "box" | "do" | "final" | "macro" | "override" | "priv"
        | "try" | "typeof" | "unsized" | "virtual" | "yield" => format!("{s}_field"),
        _ => s.to_owned(),
    }
}
