use std::fmt::Write;

use crate::config::TargetConfig;
use crate::ir::{CPrimitive, CTypeRef, Registry};
use crate::type_map::map_primitive;

use super::{field_name, snake_case};

/// Emit `mappers.rs` — one `map_<name>()` function per struct that converts a
/// decoded Rust struct into a proto message struct.
///
/// The generated code uses explicit field-by-field assignment to make the
/// mapping visible and auditable.
pub fn emit(registry: &Registry, config: TargetConfig) -> String {
    let mut out = String::new();

    writeln!(out, "// Generated by header-gen.").unwrap();
    writeln!(
        out,
        "// Target: endian={}, word_size={}",
        config.endian, config.word_size
    )
    .unwrap();
    writeln!(out, "#![allow(dead_code)]").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use crate::structs;").unwrap();
    writeln!(out, "use crate::proto;").unwrap();
    writeln!(out).unwrap();

    let mut names: Vec<&String> = registry.keys().collect();
    names.sort();

    for name in names {
        let s = &registry[name];
        let snake = snake_case(name);

        writeln!(
            out,
            "pub fn map_{snake}(src: &structs::{name}) -> proto::{name} {{"
        )
        .unwrap();
        writeln!(out, "    proto::{name} {{").unwrap();

        for field in &s.fields {
            if field.bitfield_width.is_some() {
                writeln!(
                    out,
                    "        // bitfield `{}` omitted — see review report",
                    field.name
                )
                .unwrap();
                continue;
            }

            let fname = field_name(&field.name);
            let expr = map_expr(&field.ty, &fname, config);
            writeln!(out, "        {fname}: {expr},").unwrap();
        }

        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    out
}

fn map_expr(ty: &CTypeRef, fname: &str, config: TargetConfig) -> String {
    match ty {
        CTypeRef::Primitive(p) => {
            let m = map_primitive(*p, config);
            // Emit a cast when the Rust type differs from what proto expects.
            // Proto numeric fields are represented as i32/i64/u32/u64/f32/f64.
            let need_cast = matches!(
                p,
                CPrimitive::Char | CPrimitive::UChar | CPrimitive::Short | CPrimitive::UShort
            );
            if need_cast {
                let proto_rust_ty = proto_rust_ty(m.proto_type);
                format!("src.{fname} as {proto_rust_ty}")
            } else {
                format!("src.{fname}")
            }
        }
        CTypeRef::Array(elem, _count) => match elem.as_ref() {
            CTypeRef::Primitive(CPrimitive::Char) | CTypeRef::Primitive(CPrimitive::UChar) => {
                format!("src.{fname}.to_vec()")
            }
            CTypeRef::Primitive(p) => {
                let m = map_primitive(*p, config);
                let suffix = config.from_bytes_suffix();
                // Serialize array elements to bytes using the correct endianness.
                format!(
                    "src.{fname}.iter().flat_map(|v| {rust_ty}::{suffix}(*v).to_vec()).collect()",
                    rust_ty = m.rust_type,
                    suffix = suffix
                )
            }
            _ => format!("src.{fname}.to_vec()"),
        },
        CTypeRef::Struct(sname) => {
            let snake = snake_case(sname);
            format!("map_{snake}(&src.{fname})")
        }
        CTypeRef::Union { .. } => format!("src.{fname}.to_vec()"),
        CTypeRef::Unresolved(_) => "Default::default()".to_owned(),
    }
}

/// The Rust type that the proto representation uses for a given proto scalar
/// type.
fn proto_rust_ty(proto_type: &str) -> &str {
    match proto_type {
        "int32" => "i32",
        "uint32" => "u32",
        "int64" => "i64",
        "uint64" => "u64",
        "float" => "f32",
        "double" => "f64",
        "bool" => "bool",
        "bytes" => "Vec<u8>",
        _ => "i32",
    }
}
