use std::fmt::Write;

use crate::config::TargetConfig;
use crate::ir::{CTypeRef, Registry};
use crate::type_map::map_primitive;

use super::snake_case;

/// Emit a `messages.proto` file containing all structs in `registry`.
///
/// Structs are emitted in alphabetical order for deterministic output.
/// Bitfield fields are skipped (a comment notes they appear in the review
/// report).  Union fields become `bytes` placeholders.
pub fn emit(registry: &Registry, config: TargetConfig) -> String {
    let mut out = String::new();

    writeln!(out, "syntax = \"proto3\";").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "// Generated by header-gen.").unwrap();
    writeln!(
        out,
        "// Target: endian={}, word_size={}",
        config.endian, config.word_size
    )
    .unwrap();
    writeln!(out).unwrap();

    let mut names: Vec<&String> = registry.keys().collect();
    names.sort();

    for name in names {
        let s = &registry[name];
        writeln!(out, "message {} {{", name).unwrap();

        let mut tag = 1u32;
        let mut has_bitfields = false;

        for field in &s.fields {
            if field.bitfield_width.is_some() {
                has_bitfields = true;
                continue;
            }

            let fname = snake_case(&field.name);
            match &field.ty {
                crate::ir::CTypeRef::Union { .. } => {
                    writeln!(out, "    bytes {fname} = {tag}; // union placeholder").unwrap();
                }
                crate::ir::CTypeRef::Unresolved(type_name) => {
                    writeln!(
                        out,
                        "    bytes {fname} = {tag}; // unresolved type: {type_name}"
                    )
                    .unwrap();
                }
                _ => {
                    let proto_ty = proto_type(&field.ty, config);
                    writeln!(out, "    {proto_ty} {fname} = {tag};").unwrap();
                }
            }
            tag += 1;
        }

        if has_bitfields {
            writeln!(out, "    // bitfields omitted — see review report").unwrap();
        }

        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    out
}

fn proto_type(ty: &CTypeRef, config: TargetConfig) -> String {
    match ty {
        CTypeRef::Primitive(p) => map_primitive(*p, config).proto_type.to_owned(),
        CTypeRef::Array(elem, _count) => {
            // char/uchar arrays → bytes; anything else → bytes too (opaque)
            match elem.as_ref() {
                CTypeRef::Primitive(crate::ir::CPrimitive::Char)
                | CTypeRef::Primitive(crate::ir::CPrimitive::UChar) => "bytes".to_owned(),
                _ => "bytes".to_owned(),
            }
        }
        CTypeRef::Struct(name) => name.clone(),
        CTypeRef::Union { .. } => "bytes // union placeholder".to_owned(),
        CTypeRef::Unresolved(name) => format!("bytes // unresolved: {name}"),
    }
}
