use std::fmt::Write;

use crate::config::TargetConfig;
use crate::ir::{CField, CPrimitive, CStruct, CTypeRef, Registry};
use crate::type_map::{decode_expr, map_primitive};

use super::field_name;

/// Emit `structs.rs` — one Rust struct per C struct, with:
///   - `#[derive(Debug, Clone, PartialEq)]`
///   - `pub fn decode(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>>`
///   - `pub fn byte_size() -> usize`
///
/// Bitfield fields are omitted with a comment.
/// Union fields become `[u8; N]`.
pub fn emit(registry: &Registry, config: TargetConfig) -> String {
    let mut out = String::new();

    writeln!(out, "// Generated by header-gen.").unwrap();
    writeln!(
        out,
        "// Target: endian={}, word_size={}",
        config.endian, config.word_size
    )
    .unwrap();
    writeln!(out, "#![allow(dead_code)]").unwrap();
    writeln!(out).unwrap();

    let mut names: Vec<&String> = registry.keys().collect();
    names.sort();

    for name in names {
        let s = &registry[name];
        emit_struct(&mut out, s, config);
        out.push('\n');
    }

    out
}

fn emit_struct(out: &mut String, s: &CStruct, config: TargetConfig) {
    writeln!(out, "#[derive(Debug, Clone, PartialEq)]").unwrap();
    writeln!(out, "pub struct {} {{", s.name).unwrap();

    for field in &s.fields {
        if field.bitfield_width.is_some() {
            writeln!(
                out,
                "    // bitfield `{}` omitted — see review report",
                field.name
            )
            .unwrap();
            continue;
        }
        let rust_ty = rust_type(&field.ty, config);
        let fname = field_name(&field.name);
        writeln!(out, "    pub {fname}: {rust_ty},").unwrap();
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // impl block
    writeln!(out, "impl {} {{", s.name).unwrap();
    emit_decode(out, s, config);
    writeln!(out).unwrap();
    writeln!(
        out,
        "    pub fn byte_size() -> usize {{ {} }}",
        s.total_byte_size
    )
    .unwrap();
    writeln!(out, "}}").unwrap();
}

fn emit_decode(out: &mut String, s: &CStruct, config: TargetConfig) {
    let suffix = config.from_bytes_suffix();

    writeln!(
        out,
        "    pub fn decode(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {{"
    )
    .unwrap();
    writeln!(out, "        let mut _ofs: usize = 0;").unwrap();

    // Active (non-bitfield) fields
    let active_fields: Vec<&CField> = s
        .fields
        .iter()
        .filter(|f| f.bitfield_width.is_none())
        .collect();

    for field in &active_fields {
        let fname = field_name(&field.name);
        emit_field_decode(out, &fname, &field.ty, config, suffix);
    }

    writeln!(out, "        Ok(Self {{").unwrap();
    for field in &active_fields {
        let fname = field_name(&field.name);
        writeln!(out, "            {fname},").unwrap();
    }
    writeln!(out, "        }})").unwrap();
    writeln!(out, "    }}").unwrap();
}

fn emit_field_decode(
    out: &mut String,
    fname: &str,
    ty: &CTypeRef,
    config: TargetConfig,
    suffix: &str,
) {
    match ty {
        CTypeRef::Primitive(p) => {
            let m = map_primitive(*p, config);
            let expr = decode_expr(m.rust_type, m.byte_size, suffix);
            writeln!(out, "        let {fname} = {expr};").unwrap();
            writeln!(out, "        _ofs += {};", m.byte_size).unwrap();
        }
        CTypeRef::Array(elem, count) => {
            emit_array_decode(out, fname, elem, *count, config, suffix);
        }
        CTypeRef::Struct(sname) => {
            writeln!(
                out,
                "        let {fname} = {sname}::decode(&bytes[_ofs..])?;"
            )
            .unwrap();
            writeln!(out, "        _ofs += {sname}::byte_size();").unwrap();
        }
        CTypeRef::Union { byte_size } => {
            writeln!(
                out,
                "        let {fname}: [u8; {byte_size}] = bytes[_ofs.._ofs + {byte_size}].try_into()?;"
            )
            .unwrap();
            writeln!(out, "        _ofs += {byte_size};").unwrap();
        }
        CTypeRef::Unresolved(name) => {
            writeln!(
                out,
                "        // FIXME: unresolved type `{name}` for field `{fname}`"
            )
            .unwrap();
            writeln!(out, "        let {fname} = ();").unwrap();
        }
    }
}

fn emit_array_decode(
    out: &mut String,
    fname: &str,
    elem: &CTypeRef,
    count: u64,
    config: TargetConfig,
    suffix: &str,
) {
    match elem {
        // char[N] / uchar[N] → [u8; N]
        CTypeRef::Primitive(CPrimitive::Char) | CTypeRef::Primitive(CPrimitive::UChar) => {
            writeln!(
                out,
                "        let {fname}: [u8; {count}] = bytes[_ofs.._ofs + {count}].try_into()?;"
            )
            .unwrap();
            writeln!(out, "        _ofs += {count};").unwrap();
        }
        CTypeRef::Primitive(p) => {
            let m = map_primitive(*p, config);
            let elem_size = m.byte_size;
            let rust_ty = m.rust_type;
            writeln!(out, "        let {fname}: [{rust_ty}; {count}] = {{").unwrap();
            writeln!(
                out,
                "            let mut _arr = [{rust_ty}::default(); {count}];"
            )
            .unwrap();
            writeln!(out, "            for _i in 0..{count} {{").unwrap();
            let expr = decode_expr(rust_ty, elem_size, suffix);
            writeln!(out, "                _arr[_i] = {expr};").unwrap();
            writeln!(out, "                _ofs += {elem_size};").unwrap();
            writeln!(out, "            }}").unwrap();
            writeln!(out, "            _arr").unwrap();
            writeln!(out, "        }};").unwrap();
        }
        _ => {
            // Fallback: treat as raw bytes
            let total = count; // best effort
            writeln!(
                out,
                "        let {fname}: [u8; {total}] = bytes[_ofs.._ofs + {total}].try_into()?;"
            )
            .unwrap();
            writeln!(out, "        _ofs += {total};").unwrap();
        }
    }
}

fn rust_type(ty: &CTypeRef, config: TargetConfig) -> String {
    match ty {
        CTypeRef::Primitive(p) => map_primitive(*p, config).rust_type.to_owned(),
        CTypeRef::Array(elem, count) => match elem.as_ref() {
            CTypeRef::Primitive(CPrimitive::Char) | CTypeRef::Primitive(CPrimitive::UChar) => {
                format!("[u8; {count}]")
            }
            _ => {
                let inner = rust_type(elem, config);
                format!("[{inner}; {count}]")
            }
        },
        CTypeRef::Struct(name) => name.clone(),
        CTypeRef::Union { byte_size } => format!("[u8; {byte_size}]"),
        CTypeRef::Unresolved(_) => "()".to_owned(),
    }
}
