//! spear-gateway — decode pipeline for SPEAR messages.
//!
//! Reads raw binary bytes from a file or the legacy broker and decodes them
//! using types generated by `spear-gen`.
//!
//! ## Setup (classified side)
//!
//! 1. Generate types from your real XSDs:
//!    ```bash
//!    spear-gen --input /workspace/xsds \
//!              --out-proto /workspace/types.proto \
//!              --out-rust   src/types.rs
//!    ```
//!
//! 2. Uncomment `include!("types.rs");` below.
//!
//! 3. Add your `decode_raw` call inside `decode_and_print`.
//!
//! 4. Rebuild:
//!    ```bash
//!    cargo build --offline --release -p spear-gateway
//!    ```

use anyhow::{Context, Result};
use clap::Parser;

// ─── generated types ─────────────────────────────────────────────────────────
// Paste the path to your spear-gen output and uncomment:
//
//   include!("types.rs");
//
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Parser)]
#[command(name = "spear-gateway", about = "Decode SPEAR binary messages")]
struct Args {
    /// Read raw binary from a file and decode it.
    #[arg(long, group = "source")]
    file: Option<std::path::PathBuf>,

    /// Connect to the legacy broker (C integration — not yet implemented).
    #[arg(long, group = "source")]
    live: bool,

    /// Treat the binary as little-endian (same endianness as this host).
    /// Pass --big-endian if the source system is big-endian.
    #[arg(long, default_value_t = true)]
    same_endianness: bool,
}

fn main() -> Result<()> {
    let args = Args::parse();

    if args.live {
        // Live broker mode: bytes will arrive from the legacy C broker.
        // Wire up the C subscription here once the integration is ready,
        // then pass each message buffer to decode_and_print().
        eprintln!("live broker mode: not yet implemented");
        std::process::exit(1);
    }

    let path = args
        .file
        .as_ref()
        .context("specify --file <path> or --live")?;

    let bytes = std::fs::read(path).with_context(|| format!("reading {}", path.display()))?;

    eprintln!("read {} bytes from {}", bytes.len(), path.display());

    decode_and_print(&bytes, args.same_endianness);

    Ok(())
}

fn decode_and_print(bytes: &[u8], _same_endianness: bool) {
    // Replace this block with your decode_raw call once types.rs is in place:
    //
    //   match TrackMessage::decode_raw(bytes, _same_endianness) {
    //       Ok((msg, _sz)) => println!("{msg:#?}"),
    //       Err(e)         => eprintln!("decode error: {e}"),
    //   }

    eprintln!("raw ({} bytes): {}", bytes.len(), hex_dump(bytes, 64));
    eprintln!("TODO: uncomment include!(\"types.rs\") and add decode_raw call");
}

/// Hex-dump up to `limit` bytes with a trailing note if truncated.
fn hex_dump(bytes: &[u8], limit: usize) -> String {
    let truncated = bytes.len() > limit;
    let slice = &bytes[..bytes.len().min(limit)];
    let hex = slice
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect::<Vec<_>>()
        .join(" ");
    if truncated {
        format!("{hex} ... ({} bytes total)", bytes.len())
    } else {
        hex
    }
}
