// Auto-generated by spear-gen. DO NOT EDIT.

use prost::Message;
use serde::{Deserialize, Serialize};

mod _codec {
    //! Low-level helpers used by the generated decode_raw / encode_raw impls.

    // ── read helpers ──────────────────────────────────────────────────────────

    pub fn read_bool(buf: &[u8], offset: usize) -> bool {
        buf[offset] != 0
    }
    pub fn read_i32(buf: &[u8], offset: usize, same_endianness: bool) -> i32 {
        let b = &buf[offset..offset + 4];
        if same_endianness {
            i32::from_ne_bytes([b[0], b[1], b[2], b[3]])
        } else {
            i32::from_ne_bytes([b[3], b[2], b[1], b[0]])
        }
    }
    pub fn read_u32(buf: &[u8], offset: usize, same_endianness: bool) -> u32 {
        let b = &buf[offset..offset + 4];
        if same_endianness {
            u32::from_ne_bytes([b[0], b[1], b[2], b[3]])
        } else {
            u32::from_ne_bytes([b[3], b[2], b[1], b[0]])
        }
    }
    pub fn read_i64(buf: &[u8], offset: usize, same_endianness: bool) -> i64 {
        let b = &buf[offset..offset + 8];
        if same_endianness {
            i64::from_ne_bytes([b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7]])
        } else {
            i64::from_ne_bytes([b[7], b[6], b[5], b[4], b[3], b[2], b[1], b[0]])
        }
    }
    pub fn read_u64(buf: &[u8], offset: usize, same_endianness: bool) -> u64 {
        let b = &buf[offset..offset + 8];
        if same_endianness {
            u64::from_ne_bytes([b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7]])
        } else {
            u64::from_ne_bytes([b[7], b[6], b[5], b[4], b[3], b[2], b[1], b[0]])
        }
    }
    pub fn read_f32(buf: &[u8], offset: usize, same_endianness: bool) -> f32 {
        f32::from_bits(read_u32(buf, offset, same_endianness))
    }
    pub fn read_f64(buf: &[u8], offset: usize, same_endianness: bool) -> f64 {
        f64::from_bits(read_u64(buf, offset, same_endianness))
    }
    /// Read a null-terminated string. Returns (string, bytes_consumed).
    /// An immediate null byte encodes an empty/NULL string (1 byte consumed).
    pub fn read_string(
        buf: &[u8],
        offset: usize,
    ) -> Result<(String, usize), Box<dyn std::error::Error + Send + Sync>> {
        let rest = &buf[offset..];
        let null_pos = rest
            .iter()
            .position(|&b| b == 0)
            .ok_or("unterminated string in buffer")?;
        let s = String::from_utf8_lossy(&rest[..null_pos]).into_owned();
        Ok((s, null_pos + 1))
    }

    // ── write helpers ─────────────────────────────────────────────────────────

    pub fn write_bool(buf: &mut Vec<u8>, v: bool) {
        buf.push(v as u8);
    }
    pub fn write_i32(buf: &mut Vec<u8>, v: i32, same_endianness: bool) {
        let b = v.to_ne_bytes();
        if same_endianness {
            buf.extend_from_slice(&b);
        } else {
            buf.extend_from_slice(&[b[3], b[2], b[1], b[0]]);
        }
    }
    pub fn write_u32(buf: &mut Vec<u8>, v: u32, same_endianness: bool) {
        let b = v.to_ne_bytes();
        if same_endianness {
            buf.extend_from_slice(&b);
        } else {
            buf.extend_from_slice(&[b[3], b[2], b[1], b[0]]);
        }
    }
    pub fn write_i64(buf: &mut Vec<u8>, v: i64, same_endianness: bool) {
        let b = v.to_ne_bytes();
        if same_endianness {
            buf.extend_from_slice(&b);
        } else {
            buf.extend_from_slice(&[b[7], b[6], b[5], b[4], b[3], b[2], b[1], b[0]]);
        }
    }
    pub fn write_u64(buf: &mut Vec<u8>, v: u64, same_endianness: bool) {
        let b = v.to_ne_bytes();
        if same_endianness {
            buf.extend_from_slice(&b);
        } else {
            buf.extend_from_slice(&[b[7], b[6], b[5], b[4], b[3], b[2], b[1], b[0]]);
        }
    }
    pub fn write_f32(buf: &mut Vec<u8>, v: f32, same_endianness: bool) {
        write_u32(buf, v.to_bits(), same_endianness);
    }
    pub fn write_f64(buf: &mut Vec<u8>, v: f64, same_endianness: bool) {
        write_u64(buf, v.to_bits(), same_endianness);
    }
    /// Write a null-terminated string. Writes a single 0x00 for an empty string.
    pub fn write_string(buf: &mut Vec<u8>, s: &str) {
        if s.is_empty() {
            buf.push(0);
        } else {
            buf.extend_from_slice(s.as_bytes());
            buf.push(0);
        }
    }
    /// Read a length-prefixed byte blob. Returns (bytes, total_bytes_consumed).
    /// Wire format: i32 length prefix (same_endianness) + raw bytes.
    pub fn read_bytes(
        buf: &[u8],
        offset: usize,
        same_endianness: bool,
    ) -> Result<(Vec<u8>, usize), Box<dyn std::error::Error + Send + Sync>> {
        if buf.len() < offset + 4 {
            return Err("buffer too short for bytes length prefix".into());
        }
        let len = read_i32(buf, offset, same_endianness) as usize;
        let start = offset + 4;
        if buf.len() < start + len {
            return Err(format!("buffer too short for bytes payload (need {len})").into());
        }
        Ok((buf[start..start + len].to_vec(), 4 + len))
    }
    /// Write a length-prefixed byte blob.
    pub fn write_bytes(buf: &mut Vec<u8>, v: &[u8], same_endianness: bool) {
        write_i32(buf, v.len() as i32, same_endianness);
        buf.extend_from_slice(v);
    }
}

#[allow(non_camel_case_types, clippy::upper_case_acronyms)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[derive(Serialize, Deserialize)]
#[derive(prost::Enumeration)]
#[repr(i32)]
pub enum AlertSeverity {
    #[allow(non_camel_case_types)]
    #[serde(rename = "Info")]
    Info = 0,
    #[allow(non_camel_case_types)]
    #[serde(rename = "Warning")]
    Warning = 1,
    #[allow(non_camel_case_types)]
    #[serde(rename = "Critical")]
    Critical = 2,
}

#[allow(non_camel_case_types, clippy::upper_case_acronyms)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[derive(Serialize, Deserialize)]
#[derive(prost::Enumeration)]
#[repr(i32)]
pub enum AlertType {
    #[allow(non_camel_case_types)]
    #[serde(rename = "SystemAlert")]
    SystemAlert = 0,
    #[allow(non_camel_case_types)]
    #[serde(rename = "TrackAlert")]
    TrackAlert = 1,
    #[allow(non_camel_case_types)]
    #[serde(rename = "SensorAlert")]
    SensorAlert = 2,
}

#[derive(Clone, PartialEq)]
#[derive(Message)]
#[derive(Serialize, Deserialize)]
pub struct AlertSource {
    // xs:choice — at most one of these fields will be populated
    #[prost(string, tag="1")]
    #[serde(rename = "SystemId")]
    pub system_id: String,
    #[prost(string, tag="2")]
    #[serde(rename = "SensorId")]
    pub sensor_id: String,
    #[prost(string, tag="3")]
    #[serde(rename = "OperatorId")]
    pub operator_id: String,
}

#[derive(Clone, PartialEq)]
#[derive(Message)]
#[derive(Serialize, Deserialize)]
pub struct AlertMessage {
    #[prost(string, tag="1")]
    #[serde(rename = "AlertId")]
    pub alert_id: String,
    #[prost(string, tag="2")]
    #[serde(rename = "Timestamp")]
    pub timestamp: String,
    #[prost(enumeration="AlertSeverity", tag="3")]
    #[serde(rename = "Severity")]
    pub severity: i32,
    #[prost(enumeration="AlertType", tag="4")]
    #[serde(rename = "Type")]
    pub type_field: i32,
    #[prost(message, tag="5")]
    #[serde(rename = "Source")]
    pub source: Option<AlertSource>,
    #[prost(string, tag="6")]
    #[serde(rename = "Description")]
    pub description: String,
    #[prost(string, repeated, tag="7")]
    #[serde(rename = "RelatedTrackIds")]
    pub related_track_ids: Vec<String>,
}

#[allow(non_camel_case_types, clippy::upper_case_acronyms)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[derive(Serialize, Deserialize)]
#[derive(prost::Enumeration)]
#[repr(i32)]
pub enum RecordMode {
    #[allow(non_camel_case_types)]
    #[serde(rename = "DATA_RECORD_OFF")]
    DATA_RECORD_OFF = 0,
    #[allow(non_camel_case_types)]
    #[serde(rename = "DATA_RECORD_ON")]
    DATA_RECORD_ON = 1,
    #[allow(non_camel_case_types)]
    #[serde(rename = "DATA_RECORD_PAUSED")]
    DATA_RECORD_PAUSED = 2,
}

#[allow(non_camel_case_types, clippy::upper_case_acronyms)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[derive(Serialize, Deserialize)]
#[derive(prost::Enumeration)]
#[repr(i32)]
pub enum SystemState {
    #[allow(non_camel_case_types)]
    #[serde(rename = "Offline")]
    Offline = 0,
    #[allow(non_camel_case_types)]
    #[serde(rename = "Initializing")]
    Initializing = 1,
    #[allow(non_camel_case_types)]
    #[serde(rename = "Operational")]
    Operational = 2,
    #[allow(non_camel_case_types)]
    #[serde(rename = "Degraded")]
    Degraded = 3,
    #[allow(non_camel_case_types)]
    #[serde(rename = "Fault")]
    Fault = 4,
}

#[derive(Clone, PartialEq)]
#[derive(Message)]
#[derive(Serialize, Deserialize)]
pub struct BaseMessage {
    #[prost(string, tag="1")]
    #[serde(rename = "MessageId")]
    pub message_id: String,
    #[prost(string, tag="2")]
    #[serde(rename = "Timestamp")]
    pub timestamp: String,
    #[prost(string, tag="3")]
    #[serde(rename = "SourceSystemId")]
    pub source_system_id: String,
}

#[derive(Clone, PartialEq)]
#[derive(Message)]
#[derive(Serialize, Deserialize)]
pub struct SensorStatus {
    #[prost(string, tag="1")]
    #[serde(rename = "SensorId")]
    pub sensor_id: String,
    #[prost(bool, tag="2")]
    #[serde(rename = "Operational")]
    pub operational: bool,
    #[prost(int32, repeated, tag="3")]
    #[serde(rename = "ErrorCodes")]
    pub error_codes: Vec<i32>,
}

#[derive(Clone, PartialEq)]
#[derive(Message)]
#[derive(Serialize, Deserialize)]
pub struct StatusMessage {
    #[prost(string, tag="1")]
    #[serde(rename = "MessageId")]
    pub message_id: String,
    #[prost(string, tag="2")]
    #[serde(rename = "Timestamp")]
    pub timestamp: String,
    #[prost(string, tag="3")]
    #[serde(rename = "SourceSystemId")]
    pub source_system_id: String,
    #[prost(enumeration="SystemState", tag="4")]
    #[serde(rename = "State")]
    pub state: i32,
    #[prost(message, repeated, tag="5")]
    #[serde(rename = "Sensors")]
    pub sensors: Vec<SensorStatus>,
}

#[derive(Clone, PartialEq)]
#[derive(Message)]
#[derive(Serialize, Deserialize)]
pub struct Credentials {
    #[prost(bytes, tag="1")]
    #[serde(rename = "Token")]
    pub token: Vec<u8>,
    #[prost(string, tag="2")]
    #[serde(rename = "Label")]
    pub label: String,
}

#[allow(non_camel_case_types, clippy::upper_case_acronyms)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[derive(Serialize, Deserialize)]
#[derive(prost::Enumeration)]
#[repr(i32)]
pub enum TrackCategory {
    #[allow(non_camel_case_types)]
    #[serde(rename = "Unknown")]
    Unknown = 0,
    #[allow(non_camel_case_types)]
    #[serde(rename = "Air")]
    Air = 1,
    #[allow(non_camel_case_types)]
    #[serde(rename = "Surface")]
    Surface = 2,
    #[allow(non_camel_case_types)]
    #[serde(rename = "Subsurface")]
    Subsurface = 3,
    #[allow(non_camel_case_types)]
    #[serde(rename = "Land")]
    Land = 4,
}

#[allow(non_camel_case_types, clippy::upper_case_acronyms)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[derive(Serialize, Deserialize)]
#[derive(prost::Enumeration)]
#[repr(i32)]
pub enum TrackQuality {
    #[allow(non_camel_case_types)]
    #[serde(rename = "Poor")]
    Poor = 0,
    #[allow(non_camel_case_types)]
    #[serde(rename = "Fair")]
    Fair = 1,
    #[allow(non_camel_case_types)]
    #[serde(rename = "Good")]
    Good = 2,
    #[allow(non_camel_case_types)]
    #[serde(rename = "Excellent")]
    Excellent = 3,
}

#[derive(Clone, PartialEq)]
#[derive(Message)]
#[derive(Serialize, Deserialize)]
pub struct Position {
    #[prost(double, tag="1")]
    #[serde(rename = "Latitude")]
    pub latitude: f64,
    #[prost(double, tag="2")]
    #[serde(rename = "Longitude")]
    pub longitude: f64,
    #[prost(double, tag="3")]
    #[serde(rename = "Altitude")]
    pub altitude: f64,
}

#[derive(Clone, PartialEq)]
#[derive(Message)]
#[derive(Serialize, Deserialize)]
pub struct Velocity {
    #[prost(double, tag="1")]
    #[serde(rename = "SpeedKnots")]
    pub speed_knots: f64,
    #[prost(double, tag="2")]
    #[serde(rename = "HeadingDeg")]
    pub heading_deg: f64,
    #[prost(double, tag="3")]
    #[serde(rename = "VerticalRateFpm")]
    pub vertical_rate_fpm: f64,
}

#[derive(Clone, PartialEq)]
#[derive(Message)]
#[derive(Serialize, Deserialize)]
pub struct TrackMessage {
    #[prost(string, tag="1")]
    #[serde(rename = "TrackId")]
    pub track_id: String,
    #[prost(string, tag="2")]
    #[serde(rename = "Timestamp")]
    pub timestamp: String,
    #[prost(enumeration="TrackCategory", tag="3")]
    #[serde(rename = "Category")]
    pub category: i32,
    #[prost(enumeration="TrackQuality", tag="4")]
    #[serde(rename = "Quality")]
    pub quality: i32,
    #[prost(message, tag="5")]
    #[serde(rename = "Position")]
    pub position: Option<Position>,
    #[prost(message, tag="6")]
    #[serde(rename = "Velocity")]
    pub velocity: Option<Velocity>,
}

#[allow(unused_variables, unused_mut)]
impl AlertSource {
    /// Decode from the custom binary wire format.
    /// Returns the decoded value and the number of bytes consumed.
    pub fn decode_raw(
        buf: &[u8],
        same_endianness: bool,
    ) -> Result<(Self, usize), Box<dyn std::error::Error + Send + Sync>> {
        let mut offset = 0usize;
        // xs:choice: decoded sequentially; verify field order against encode_raw.
        let (system_id, _n_system_id) = _codec::read_string(buf, offset)?;
        offset += _n_system_id;
        let (sensor_id, _n_sensor_id) = _codec::read_string(buf, offset)?;
        offset += _n_sensor_id;
        let (operator_id, _n_operator_id) = _codec::read_string(buf, offset)?;
        offset += _n_operator_id;
        Ok((Self {
            system_id,
            sensor_id,
            operator_id,
        }, offset))
    }

    /// Encode into the custom binary wire format, appending to `buf`.
    pub fn encode_raw(&self, buf: &mut Vec<u8>, same_endianness: bool) {
        _codec::write_string(buf, &self.system_id);
        _codec::write_string(buf, &self.sensor_id);
        _codec::write_string(buf, &self.operator_id);
    }

    /// Returns the number of bytes this value occupies in the binary wire format.
    pub fn encoded_size(&self) -> usize {
        let mut size = 0usize;
        size += if self.system_id.is_empty() { 1 } else { self.system_id.len() + 1 };
        size += if self.sensor_id.is_empty() { 1 } else { self.sensor_id.len() + 1 };
        size += if self.operator_id.is_empty() { 1 } else { self.operator_id.len() + 1 };
        size
    }
}

#[allow(unused_variables, unused_mut)]
impl AlertMessage {
    /// Decode from the custom binary wire format.
    /// Returns the decoded value and the number of bytes consumed.
    pub fn decode_raw(
        buf: &[u8],
        same_endianness: bool,
    ) -> Result<(Self, usize), Box<dyn std::error::Error + Send + Sync>> {
        let mut offset = 0usize;
        let (alert_id, _n_alert_id) = _codec::read_string(buf, offset)?;
        offset += _n_alert_id;
        let (timestamp, _n_timestamp) = _codec::read_string(buf, offset)?;
        offset += _n_timestamp;
        let severity = _codec::read_i32(buf, offset, same_endianness);
        offset += 4;
        let type_field = _codec::read_i32(buf, offset, same_endianness);
        offset += 4;
        let (source, _n_source) = AlertSource::decode_raw(&buf[offset..], same_endianness)?;
        offset += _n_source;
        let (description, _n_description) = _codec::read_string(buf, offset)?;
        offset += _n_description;
        let _related_track_ids_count = _codec::read_i32(buf, offset, same_endianness) as usize;
        offset += 4;
        if _related_track_ids_count > 65535 { return Err(format!("array 'related_track_ids' count {} unreasonably large", _related_track_ids_count).into()); }
        let mut related_track_ids = Vec::with_capacity(_related_track_ids_count);
        for _ in 0.._related_track_ids_count {
            let (_elem, _elem_n) = _codec::read_string(buf, offset)?;
            offset += _elem_n;
            related_track_ids.push(_elem);
        }
        Ok((Self {
            alert_id,
            timestamp,
            severity,
            type_field,
            source: Some(source),
            description,
            related_track_ids,
        }, offset))
    }

    /// Encode into the custom binary wire format, appending to `buf`.
    pub fn encode_raw(&self, buf: &mut Vec<u8>, same_endianness: bool) {
        _codec::write_string(buf, &self.alert_id);
        _codec::write_string(buf, &self.timestamp);
        _codec::write_i32(buf, self.severity, same_endianness);
        _codec::write_i32(buf, self.type_field, same_endianness);
        if let Some(v) = &self.source { v.encode_raw(buf, same_endianness); }
        _codec::write_string(buf, &self.description);
        _codec::write_i32(buf, self.related_track_ids.len() as i32, same_endianness);
        for item in &self.related_track_ids { _codec::write_string(buf, item); }
    }

    /// Returns the number of bytes this value occupies in the binary wire format.
    pub fn encoded_size(&self) -> usize {
        let mut size = 0usize;
        size += if self.alert_id.is_empty() { 1 } else { self.alert_id.len() + 1 };
        size += if self.timestamp.is_empty() { 1 } else { self.timestamp.len() + 1 };
        size += 4;
        size += 4;
        size += self.source.as_ref().map(|v| v.encoded_size()).unwrap_or(0);
        size += if self.description.is_empty() { 1 } else { self.description.len() + 1 };
        size += 4;
        size += self.related_track_ids.iter().map(|s| if s.is_empty() { 1 } else { s.len() + 1 }).sum::<usize>();
        size
    }
}

#[allow(unused_variables, unused_mut)]
impl BaseMessage {
    /// Decode from the custom binary wire format.
    /// Returns the decoded value and the number of bytes consumed.
    pub fn decode_raw(
        buf: &[u8],
        same_endianness: bool,
    ) -> Result<(Self, usize), Box<dyn std::error::Error + Send + Sync>> {
        let mut offset = 0usize;
        let (message_id, _n_message_id) = _codec::read_string(buf, offset)?;
        offset += _n_message_id;
        let (timestamp, _n_timestamp) = _codec::read_string(buf, offset)?;
        offset += _n_timestamp;
        let (source_system_id, _n_source_system_id) = _codec::read_string(buf, offset)?;
        offset += _n_source_system_id;
        Ok((Self {
            message_id,
            timestamp,
            source_system_id,
        }, offset))
    }

    /// Encode into the custom binary wire format, appending to `buf`.
    pub fn encode_raw(&self, buf: &mut Vec<u8>, same_endianness: bool) {
        _codec::write_string(buf, &self.message_id);
        _codec::write_string(buf, &self.timestamp);
        _codec::write_string(buf, &self.source_system_id);
    }

    /// Returns the number of bytes this value occupies in the binary wire format.
    pub fn encoded_size(&self) -> usize {
        let mut size = 0usize;
        size += if self.message_id.is_empty() { 1 } else { self.message_id.len() + 1 };
        size += if self.timestamp.is_empty() { 1 } else { self.timestamp.len() + 1 };
        size += if self.source_system_id.is_empty() { 1 } else { self.source_system_id.len() + 1 };
        size
    }
}

#[allow(unused_variables, unused_mut)]
impl SensorStatus {
    /// Decode from the custom binary wire format.
    /// Returns the decoded value and the number of bytes consumed.
    pub fn decode_raw(
        buf: &[u8],
        same_endianness: bool,
    ) -> Result<(Self, usize), Box<dyn std::error::Error + Send + Sync>> {
        let mut offset = 0usize;
        let (sensor_id, _n_sensor_id) = _codec::read_string(buf, offset)?;
        offset += _n_sensor_id;
        let operational = _codec::read_bool(buf, offset);
        offset += 1;
        let _error_codes_count = _codec::read_i32(buf, offset, same_endianness) as usize;
        offset += 4;
        if _error_codes_count > 65535 { return Err(format!("array 'error_codes' count {} unreasonably large", _error_codes_count).into()); }
        let mut error_codes = Vec::with_capacity(_error_codes_count);
        for _ in 0.._error_codes_count {
            error_codes.push(_codec::read_i32(buf, offset, same_endianness));
            offset += 4;
        }
        Ok((Self {
            sensor_id,
            operational,
            error_codes,
        }, offset))
    }

    /// Encode into the custom binary wire format, appending to `buf`.
    pub fn encode_raw(&self, buf: &mut Vec<u8>, same_endianness: bool) {
        _codec::write_string(buf, &self.sensor_id);
        _codec::write_bool(buf, self.operational);
        _codec::write_i32(buf, self.error_codes.len() as i32, same_endianness);
        for &item in &self.error_codes { _codec::write_i32(buf, item, same_endianness); }
    }

    /// Returns the number of bytes this value occupies in the binary wire format.
    pub fn encoded_size(&self) -> usize {
        let mut size = 0usize;
        size += if self.sensor_id.is_empty() { 1 } else { self.sensor_id.len() + 1 };
        size += 1;
        size += 4;
        size += self.error_codes.len() * 4;
        size
    }
}

#[allow(unused_variables, unused_mut)]
impl StatusMessage {
    /// Decode from the custom binary wire format.
    /// Returns the decoded value and the number of bytes consumed.
    pub fn decode_raw(
        buf: &[u8],
        same_endianness: bool,
    ) -> Result<(Self, usize), Box<dyn std::error::Error + Send + Sync>> {
        let mut offset = 0usize;
        let (message_id, _n_message_id) = _codec::read_string(buf, offset)?;
        offset += _n_message_id;
        let (timestamp, _n_timestamp) = _codec::read_string(buf, offset)?;
        offset += _n_timestamp;
        let (source_system_id, _n_source_system_id) = _codec::read_string(buf, offset)?;
        offset += _n_source_system_id;
        let state = _codec::read_i32(buf, offset, same_endianness);
        offset += 4;
        let _sensors_count = _codec::read_i32(buf, offset, same_endianness) as usize;
        offset += 4;
        if _sensors_count > 65535 { return Err(format!("array 'sensors' count {} unreasonably large", _sensors_count).into()); }
        let mut sensors = Vec::with_capacity(_sensors_count);
        for _ in 0.._sensors_count {
            let (_elem, _elem_size) = SensorStatus::decode_raw(&buf[offset..], same_endianness)?;
            offset += _elem_size;
            sensors.push(_elem);
        }
        Ok((Self {
            message_id,
            timestamp,
            source_system_id,
            state,
            sensors,
        }, offset))
    }

    /// Encode into the custom binary wire format, appending to `buf`.
    pub fn encode_raw(&self, buf: &mut Vec<u8>, same_endianness: bool) {
        _codec::write_string(buf, &self.message_id);
        _codec::write_string(buf, &self.timestamp);
        _codec::write_string(buf, &self.source_system_id);
        _codec::write_i32(buf, self.state, same_endianness);
        _codec::write_i32(buf, self.sensors.len() as i32, same_endianness);
        for item in &self.sensors { item.encode_raw(buf, same_endianness); }
    }

    /// Returns the number of bytes this value occupies in the binary wire format.
    pub fn encoded_size(&self) -> usize {
        let mut size = 0usize;
        size += if self.message_id.is_empty() { 1 } else { self.message_id.len() + 1 };
        size += if self.timestamp.is_empty() { 1 } else { self.timestamp.len() + 1 };
        size += if self.source_system_id.is_empty() { 1 } else { self.source_system_id.len() + 1 };
        size += 4;
        size += 4;
        size += self.sensors.iter().map(|e| e.encoded_size()).sum::<usize>();
        size
    }
}

#[allow(unused_variables, unused_mut)]
impl Credentials {
    /// Decode from the custom binary wire format.
    /// Returns the decoded value and the number of bytes consumed.
    pub fn decode_raw(
        buf: &[u8],
        same_endianness: bool,
    ) -> Result<(Self, usize), Box<dyn std::error::Error + Send + Sync>> {
        let mut offset = 0usize;
        let (token, _n_token) = _codec::read_bytes(buf, offset, same_endianness)?;
        offset += _n_token;
        let (label, _n_label) = _codec::read_string(buf, offset)?;
        offset += _n_label;
        Ok((Self {
            token,
            label,
        }, offset))
    }

    /// Encode into the custom binary wire format, appending to `buf`.
    pub fn encode_raw(&self, buf: &mut Vec<u8>, same_endianness: bool) {
        _codec::write_bytes(buf, &self.token, same_endianness);
        _codec::write_string(buf, &self.label);
    }

    /// Returns the number of bytes this value occupies in the binary wire format.
    pub fn encoded_size(&self) -> usize {
        let mut size = 0usize;
        size += 4 + self.token.len();
        size += if self.label.is_empty() { 1 } else { self.label.len() + 1 };
        size
    }
}

#[allow(unused_variables, unused_mut)]
impl Position {
    /// Decode from the custom binary wire format.
    /// Returns the decoded value and the number of bytes consumed.
    pub fn decode_raw(
        buf: &[u8],
        same_endianness: bool,
    ) -> Result<(Self, usize), Box<dyn std::error::Error + Send + Sync>> {
        let mut offset = 0usize;
        let latitude = _codec::read_f64(buf, offset, same_endianness);
        offset += 8;
        let longitude = _codec::read_f64(buf, offset, same_endianness);
        offset += 8;
        let altitude = _codec::read_f64(buf, offset, same_endianness);
        offset += 8;
        Ok((Self {
            latitude,
            longitude,
            altitude,
        }, offset))
    }

    /// Encode into the custom binary wire format, appending to `buf`.
    pub fn encode_raw(&self, buf: &mut Vec<u8>, same_endianness: bool) {
        _codec::write_f64(buf, self.latitude, same_endianness);
        _codec::write_f64(buf, self.longitude, same_endianness);
        _codec::write_f64(buf, self.altitude, same_endianness);
    }

    /// Returns the number of bytes this value occupies in the binary wire format.
    pub fn encoded_size(&self) -> usize {
        let mut size = 0usize;
        size += 8;
        size += 8;
        size += 8;
        size
    }
}

#[allow(unused_variables, unused_mut)]
impl Velocity {
    /// Decode from the custom binary wire format.
    /// Returns the decoded value and the number of bytes consumed.
    pub fn decode_raw(
        buf: &[u8],
        same_endianness: bool,
    ) -> Result<(Self, usize), Box<dyn std::error::Error + Send + Sync>> {
        let mut offset = 0usize;
        let speed_knots = _codec::read_f64(buf, offset, same_endianness);
        offset += 8;
        let heading_deg = _codec::read_f64(buf, offset, same_endianness);
        offset += 8;
        let vertical_rate_fpm = _codec::read_f64(buf, offset, same_endianness);
        offset += 8;
        Ok((Self {
            speed_knots,
            heading_deg,
            vertical_rate_fpm,
        }, offset))
    }

    /// Encode into the custom binary wire format, appending to `buf`.
    pub fn encode_raw(&self, buf: &mut Vec<u8>, same_endianness: bool) {
        _codec::write_f64(buf, self.speed_knots, same_endianness);
        _codec::write_f64(buf, self.heading_deg, same_endianness);
        _codec::write_f64(buf, self.vertical_rate_fpm, same_endianness);
    }

    /// Returns the number of bytes this value occupies in the binary wire format.
    pub fn encoded_size(&self) -> usize {
        let mut size = 0usize;
        size += 8;
        size += 8;
        size += 8;
        size
    }
}

#[allow(unused_variables, unused_mut)]
impl TrackMessage {
    /// Decode from the custom binary wire format.
    /// Returns the decoded value and the number of bytes consumed.
    pub fn decode_raw(
        buf: &[u8],
        same_endianness: bool,
    ) -> Result<(Self, usize), Box<dyn std::error::Error + Send + Sync>> {
        let mut offset = 0usize;
        let (track_id, _n_track_id) = _codec::read_string(buf, offset)?;
        offset += _n_track_id;
        let (timestamp, _n_timestamp) = _codec::read_string(buf, offset)?;
        offset += _n_timestamp;
        let category = _codec::read_i32(buf, offset, same_endianness);
        offset += 4;
        let quality = _codec::read_i32(buf, offset, same_endianness);
        offset += 4;
        let (position, _n_position) = Position::decode_raw(&buf[offset..], same_endianness)?;
        offset += _n_position;
        let velocity_present = _codec::read_bool(buf, offset);
        offset += 1;
        let velocity = if velocity_present {
            let (v, n) = Velocity::decode_raw(&buf[offset..], same_endianness)?;
            offset += n;
            Some(v)
        } else {
            None
        };
        Ok((Self {
            track_id,
            timestamp,
            category,
            quality,
            position: Some(position),
            velocity,
        }, offset))
    }

    /// Encode into the custom binary wire format, appending to `buf`.
    pub fn encode_raw(&self, buf: &mut Vec<u8>, same_endianness: bool) {
        _codec::write_string(buf, &self.track_id);
        _codec::write_string(buf, &self.timestamp);
        _codec::write_i32(buf, self.category, same_endianness);
        _codec::write_i32(buf, self.quality, same_endianness);
        if let Some(v) = &self.position { v.encode_raw(buf, same_endianness); }
        _codec::write_bool(buf, self.velocity.is_some());
        if let Some(v) = &self.velocity { v.encode_raw(buf, same_endianness); }
    }

    /// Returns the number of bytes this value occupies in the binary wire format.
    pub fn encoded_size(&self) -> usize {
        let mut size = 0usize;
        size += if self.track_id.is_empty() { 1 } else { self.track_id.len() + 1 };
        size += if self.timestamp.is_empty() { 1 } else { self.timestamp.len() + 1 };
        size += 4;
        size += 4;
        size += self.position.as_ref().map(|v| v.encoded_size()).unwrap_or(0);
        size += 1;
        size += self.velocity.as_ref().map(|v| v.encoded_size()).unwrap_or(0);
        size
    }
}

